/**
 * Phase: emit — verify the agent has produced `reports.md` with required
 * sections. The agent writes the prose; this phase only gates on shape.
 *
 * Required sections: Overview, Brief / Spec / Tasks, QA, Code review,
 * Completion, CI / Follow-up. Final line must declare
 * `Status: COMPLETE` or `Status: PARTIAL` (PARTIAL = some artifacts blocked).
 */

'use strict';

const fs = require('node:fs');
const path = require('node:path');

const { REPORTS_PHASES } = require('../../reports-phase-registry');

const REPORT_FILE = 'reports.md';
const REQUIRED_SECTIONS = [
  /^##\s+Overview\b/im,
  /^##\s+Brief\s*\/\s*Spec\s*\/\s*Tasks\b/im,
  /^##\s+QA\b/im,
  /^##\s+Code review\b/im,
  /^##\s+Completion\b/im,
  /^##\s+CI\s*\/\s*Follow-up\b/im,
];
const STATUS_RE = /^Status:\s*(COMPLETE|PARTIAL)\b/im;

function validate(ctx) {
  const p = path.join(ctx.tasksDir, REPORT_FILE);
  if (!fs.existsSync(p)) {
    return {
      ok: false,
      errors: [
        `\`${REPORT_FILE}\` missing. Author the cross-step summary using \`reports-summary.json\`.`,
      ],
    };
  }
  let text;
  try {
    text = fs.readFileSync(p, 'utf8');
  } catch (e) {
    return { ok: false, errors: [`could not read \`${REPORT_FILE}\`: ${e.message}`] };
  }
  const missing = [];
  const names = [
    '## Overview',
    '## Brief / Spec / Tasks',
    '## QA',
    '## Code review',
    '## Completion',
    '## CI / Follow-up',
  ];
  REQUIRED_SECTIONS.forEach((re, i) => {
    if (!re.test(text)) missing.push(names[i]);
  });
  if (missing.length) {
    return { ok: false, errors: [`\`${REPORT_FILE}\` missing section(s): ${missing.join(', ')}.`] };
  }
  if (!STATUS_RE.test(text)) {
    return {
      ok: false,
      errors: [`\`${REPORT_FILE}\` missing final \`Status: COMPLETE\` or \`Status: PARTIAL\`.`],
    };
  }
  return { ok: true, summary: 'reports.md complete' };
}

function instructions(ctx) {
  return [
    '# reports-next — Phase 4 of 6: EMIT',
    `Ticket: ${ctx.ticket}`,
    '',
    'Write `reports.md` with:',
    '  ## Overview',
    '  ## Brief / Spec / Tasks',
    '  ## QA',
    '  ## Code review',
    '  ## Completion',
    '  ## CI / Follow-up',
    '  Status: COMPLETE | Status: PARTIAL',
    '',
    'Source: `reports-summary.json` (auto-generated by summarize phase).',
    '',
  ].join('\n');
}

module.exports = function register(registerPhase) {
  registerPhase(REPORTS_PHASES.emit, {
    next: REPORTS_PHASES.memorize,
    validate,
    instructions,
  });
};

module.exports.validate = validate;
module.exports.instructions = instructions;
module.exports.REPORT_FILE = REPORT_FILE;
module.exports.STATUS_RE = STATUS_RE;
