'use strict';

/**
 * Step: {{id}} — generated by factories/stepScaffold (kind=transition).
 */

const path = require('path');
const { createTransitionStep } = require(
  path.join(__dirname, '..', '..', '..', '..', '..', '..', 'factories', 'createTransitionStep')
);
const { STEPS } = require('../step-registry');

module.exports = createTransitionStep({
  id: STEPS.{{id}},
  command: '{{command}}',
  retryTo: '{{retryTo}}',
});
