#!/usr/bin/env node
/**
 * /check Setup Script
 *
 * Handles:
 * - Determining worktree path and report folder
 * - Generating CHANGES_HASH from git diff
 * - Checking if reports are up-to-date (cache validation)
 * - Creating folders and cleaning old files
 * - Analyzing impacted apps
 *
 * Usage: node check-setup.js [JIRA_TICKET_ID]
 *
 * Output: JSON object with setup variables
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const config = require(path.join(__dirname, '..', 'lib', 'config'));

// Get Jira ticket ID from args or environment
const JIRA_TICKET_ID = process.argv[2] || process.env.JIRA_TICKET_ID || '';

/**
 * Execute a shell command and return trimmed output
 */
function exec(cmd, options = {}) {
  try {
    return execSync(cmd, { encoding: 'utf8', ...options }).trim();
  } catch (error) {
    if (options.throwOnError !== false) {
      return '';
    }
    throw error;
  }
}

// Use centralized getBaseBranch() from config
const getBaseBranch = config.getBaseBranch;

/**
 * Get the main worktree path
 */
function getMainWorktreePath() {
  const output = exec('git worktree list');
  const firstLine = output.split('\n')[0];
  return firstLine.split(/\s+/)[0];
}

/**
 * Get current branch name
 */
function getBranchName() {
  return exec('git branch --show-current');
}

/**
 * Generate hash from changed file contents
 * Same changes = same hash, any line change = different hash
 * Uses -w to ignore whitespace-only changes
 */
function generateChangesHash() {
  // Use -w to ignore whitespace changes (prevents false cache misses)
  const baseBranch = getBaseBranch();
  const diff = exec(`git diff ${baseBranch}...HEAD -w`);
  if (!diff) {
    // No changes, use empty hash
    return 'no-changes';
  }

  // Use Node's crypto for hashing
  const crypto = require('crypto');
  const hash = crypto.createHash('sha256').update(diff).digest('hex');
  return hash.substring(0, 12);
}

/**
 * Check if reports are up-to-date by comparing hashes
 */
function checkReportsCache(reportFolder, currentHash) {
  const readmePath = path.join(reportFolder, 'README.md');

  if (!fs.existsSync(readmePath)) {
    return { cached: false, reason: 'No README.md found' };
  }

  const content = fs.readFileSync(readmePath, 'utf8');
  const match = content.match(/\*\*Changes Hash:\*\*\s*([a-f0-9]{12}|no-changes)/);

  if (!match) {
    return { cached: false, reason: 'No hash found in README.md' };
  }

  const cachedHash = match[1];

  if (cachedHash === currentHash) {
    return {
      cached: true,
      cachedHash,
      readme: content
    };
  }

  return {
    cached: false,
    reason: 'Hash mismatch',
    previousHash: cachedHash,
    currentHash
  };
}

/**
 * Create report folders and clean old files
 */
function setupReportFolder(reportFolder) {
  const screenshotsFolder = path.join(reportFolder, 'screenshots');

  // Create folders
  fs.mkdirSync(screenshotsFolder, { recursive: true });

  // Clean old screenshots
  if (fs.existsSync(screenshotsFolder)) {
    const files = fs.readdirSync(screenshotsFolder);
    for (const file of files) {
      if (/\.(png|jpg|jpeg)$/i.test(file)) {
        fs.unlinkSync(path.join(screenshotsFolder, file));
      }
    }
  }

  // Clean old report files (only *.check.md and README.md generated by /check command)
  // This preserves implement.md and other non-check files
  if (fs.existsSync(reportFolder)) {
    const files = fs.readdirSync(reportFolder);
    for (const file of files) {
      if (file.endsWith('.check.md') || file === 'README.md') {
        fs.unlinkSync(path.join(reportFolder, file));
      }
    }
  }
}

/**
 * Analyze which apps were changed
 */
function getImpactedApps() {
  const baseBranch = getBaseBranch();
  const output = exec(`git diff --name-only ${baseBranch}...HEAD`);
  if (!output) return [];

  const apps = new Set();
  const packages = new Set();
  const lines = output.split('\n');

  for (const line of lines) {
    const appMatch = line.match(/^apps\/([^/]+)\//);
    if (appMatch) {
      apps.add(appMatch[1]);
    }
    const pkgMatch = line.match(/^packages\/([^/]+)\//);
    if (pkgMatch) {
      packages.add(pkgMatch[1]);
    }
  }

  // If no direct app changes but packages changed, all web apps may be affected
  const webAppNames = config.webAppNames();
  if (apps.size === 0 && packages.size > 0 && webAppNames.length > 0) {
    console.error(`No direct app changes but ${packages.size} package(s) changed — including all web apps for QA`);
    return webAppNames;
  }

  return Array.from(apps).sort();
}

/**
 * Get affected files grouped by app and packages
 * Used by QA agents to trace dependencies
 */
function getAffectedFiles() {
  const baseBranch = getBaseBranch();
  const output = exec(`git diff --name-only ${baseBranch}...HEAD`);
  if (!output) return { apps: {}, packages: [] };

  const result = { apps: {}, packages: [] };
  const lines = output.split('\n').filter(Boolean);

  for (const line of lines) {
    // Check if it's an app file
    const appMatch = line.match(/^apps\/([^/]+)\/(.+)$/);
    if (appMatch) {
      const [, appName, filePath] = appMatch;
      if (!result.apps[appName]) {
        result.apps[appName] = [];
      }
      result.apps[appName].push(filePath);
      continue;
    }

    // Check if it's a package file
    const pkgMatch = line.match(/^packages\/([^/]+)\/(.+)$/);
    if (pkgMatch) {
      result.packages.push(line);
    }
  }

  return result;
}

/**
 * Load project-specific docs from a comma-separated env var.
 * @param {string} envVarName - Name of the env var (for warning messages)
 * @param {string} csvPaths - Comma-separated relative paths
 * @param {string} repoRoot - Absolute path to repo root
 * @returns {string} Concatenated file contents with headers, or empty string
 */
// Denylist of filename patterns that should never be injected into agent prompts
const DOCS_DENYLIST = ['.env', '.env.local', '.env.production', '.env.staging',
  'id_rsa', 'id_ed25519', 'credentials.json', 'service-account.json',
  '.secrets', '.tokens'];

function loadDocsFromPaths(envVarName, csvPaths, repoRoot) {
  const docPaths = (csvPaths || '').split(',').map(p => p.trim()).filter(Boolean);
  if (docPaths.length === 0) return '';

  const resolvedRoot = path.resolve(repoRoot);
  let docs = '';
  for (const relPath of docPaths) {
    // Reject absolute paths
    if (path.isAbsolute(relPath)) {
      console.error(`Warning: ${envVarName} rejects absolute path: ${relPath}`);
      continue;
    }
    // Reject secret/sensitive files by name (denylist + pattern match)
    const basename = path.basename(relPath);
    if (DOCS_DENYLIST.includes(basename) || /^\.env(\.|$)/i.test(basename) || /\.(pem|key|pfx|p12|secrets?|tokens?|credentials)$/i.test(basename)) {
      console.error(`Warning: ${envVarName} rejects sensitive file: ${relPath}`);
      continue;
    }
    // Resolve and ensure path stays within repo root
    const absPath = path.resolve(resolvedRoot, relPath);
    if (!absPath.startsWith(resolvedRoot + path.sep) && absPath !== resolvedRoot) {
      console.error(`Warning: ${envVarName} path escapes repo root: ${relPath}`);
      continue;
    }
    try {
      // Resolve symlinks to prevent symlink-based path traversal, then re-check
      const realPath = fs.realpathSync(absPath);
      if (!realPath.startsWith(resolvedRoot + path.sep)) {
        console.error(`Warning: ${envVarName} symlink escapes repo root: ${relPath}`);
        continue;
      }
      const stat = fs.statSync(realPath);
      if (!stat.isFile()) {
        console.error(`Warning: ${envVarName} path is not a file: ${relPath}`);
        continue;
      }
      const MAX_DOC_BYTES = 256 * 1024; // 256 KB cap — prevent injecting huge files into agent prompts
      if (stat.size > MAX_DOC_BYTES) {
        console.error(`Warning: ${envVarName} file too large (${stat.size} bytes, max ${MAX_DOC_BYTES}): ${relPath}`);
        continue;
      }
      // Reject untracked/gitignored files — use repo-relative path since git ls-files expects pathspecs relative to repo root
      const repoRelPath = path.relative(resolvedRoot, realPath);
      try {
        execSync(`git -C ${JSON.stringify(resolvedRoot)} ls-files --error-unmatch -- ${JSON.stringify(repoRelPath)}`, { stdio: 'ignore' });
      } catch {
        console.error(`Warning: ${envVarName} rejects untracked/gitignored file: ${relPath}`);
        continue;
      }
      // Guards passed: DOCS_DENYLIST + .env regex + resolve-prefix + realpathSync + isFile + 256KB + git-ls-files
      docs += `\n--- ${relPath} ---\n${fs.readFileSync(realPath, 'utf8')}\n`;
    } catch (readErr) {
      // Guard chain applied above: DOCS_DENYLIST → .env regex → path.resolve prefix →
      // realpathSync → stat.isFile → 256 KB size cap → git ls-files (repo-relative)
      const reason = readErr.code || readErr.message;
      console.error(`Warning: ${envVarName} skipped (${reason}): ${relPath}`);
    }
  }
  return docs;
}

/**
 * Main execution
 */
function main() {
  const mainWorktreePath = getMainWorktreePath();
  const branchName = getBranchName();

  // Determine report folder - use parent of main worktree + tasks
  const taskId = JIRA_TICKET_ID || branchName;
  const reportFolder = path.join(mainWorktreePath, '..', 'tasks', taskId);

  // Generate changes hash
  const changesHash = generateChangesHash();

  // Check cache
  const cacheResult = checkReportsCache(reportFolder, changesHash);

  // Get impacted apps
  const impactedApps = getImpactedApps();

  // Get affected files for QA dependency tracing
  const affectedFiles = getAffectedFiles();

  // Load project-specific docs for each agent type (always include all keys for stable schema)
  // Use current worktree root (not mainWorktreePath) so docs reflect the feature branch
  const currentRepoRoot = exec('git rev-parse --show-toplevel') || process.cwd();
  const docVars = ['READ_DOCS_ON_REVIEW', 'READ_DOCS_ON_QA', 'READ_DOCS_ON_DEV',
    'READ_DOCS_ON_E2E', 'READ_DOCS_ON_TEST', 'READ_DOCS_ON_STORYBOOK', 'READ_DOCS_ON_PR'];
  const loadedDocs = {};
  for (const varName of docVars) {
    const key = varName.replace('READ_DOCS_ON_', '').toLowerCase() + 'Docs';
    loadedDocs[key] = loadDocsFromPaths(varName, config[varName], currentRepoRoot);
  }

  // Output result
  const result = {
    mainWorktreePath,
    branchName,
    jiraTicketId: JIRA_TICKET_ID || null,
    reportFolder,
    changesHash,
    cache: cacheResult,
    impactedApps,
    affectedFiles,
    screenshotsFolder: path.join(reportFolder, 'screenshots')
  };

  // Always include all doc keys for stable JSON schema
  result.reviewDocs = loadedDocs.reviewDocs;
  result.qaDocs = loadedDocs.qaDocs;
  result.devDocs = loadedDocs.devDocs;
  result.e2eDocs = loadedDocs.e2eDocs;
  result.testDocs = loadedDocs.testDocs;
  result.storybookDocs = loadedDocs.storybookDocs;
  result.prDocs = loadedDocs.prDocs;

  // If not cached, setup the folder
  if (!cacheResult.cached) {
    setupReportFolder(reportFolder);
    result.foldersCreated = true;
  }

  console.log(JSON.stringify(result, null, 2));

  // Exit with code 0 if cached (skip checks), 1 if not cached (run checks)
  // Actually, let's not use exit codes - just output the JSON
  // The calling code will check result.cache.cached
}

main();
